### ISSUE TITLE
Question on SpotFi MUSIC specturm

### ISSUE THREAD

**Issue by sjeon87** [egaebel/lgtm#3]
In [lines between 646-652 of a file `csi-code/spotfi.m`](https://github.com/egaebel/lgtm/blob/master/csi-code/spotfi.m#L650):

```
for jj = 1:size(Pmusic, 2)
    % AoA loop
    for ii = 1:size(Pmusic, 1)
        Pmusic(ii, jj) = 10 * log10(Pmusic(ii, jj));% / max(Pmusic(:, jj))); 
        Pmusic(ii, jj) = abs(Pmusic(ii, jj));
    end
end
```

I think `abs` should be removed. Because MUSIC spectrum will have negative value at non-candidate in decibels , and taking `abs` to the negative value will make a non-candidate to a candidate.

If I get wrong, please let me know about it.

Regards.

**Comment by caichao** [comment]
abs(...) corresponds to the peaks in y axis, the angle corresponds to the peaks is the index.

**Comment by sjeon87** [comment]
No, I mean that taking abs(...) to -30 dB, for instance, will produce a wrong MUSIC spectrum

**Comment by egaebel** [comment]
@gsongsong 
You're absolutely right. I had this fixed in my local copy and just failed to upload the fix.
Thank you for pointing this out.
I'm uploading a commit to fix this in about 5 minutes.
