### ISSUE TITLE
In which device that carries the 5300 NIC in your experiment

### ISSUE THREAD

**Issue by talentzhy** [egaebel/lgtm#5]
I'm doing the same experiment, but I found that the phase abstracted form CSI is not stable, Can you tell me that in which device that carries the 5300 NIC in your experiment?
Thank you very much! @egaebel

**Comment by egaebel** [comment]
The phase instability is apparently a known issue in the 5300 NIC card that I didn't do anything to correct. The most in-depth discussion I found about it is here:

https://github.com/dhalperi/linux-80211n-csitool-supplementary/issues/124
